/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.awt.Color;
import java.awt.Toolkit;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;

/* @@author A0129845U
 * The DisplayWindowLayout is to initialize all the components in GUI in terms of layout
 */
public class DisplayWindowLayout extends javax.swing.JFrame {
	private static final long serialVersionUID = 1L;
	private static final String DIAMOND_ICON_FILE = "DiamondIcon.png";
	/**
	 * Creates new form DisplayWindow
	 *
	 * @throws Exception
	 */
	public DisplayWindowLayout() throws Exception {
		initComponents();
		setIcon();
		setBgColor();
		displayTime();
	}

	private void setIcon() {
		setIconImage(Toolkit.getDefaultToolkit().getImage(DIAMOND_ICON_FILE));
	}

	private void setBgColor() {
		getContentPane().setBackground(Color.WHITE);
	}

	private void displayTime() {
		Thread clock = new Thread() {
			@Override
			public void run() {
				try {
					while (true) {
						Calendar cal = new GregorianCalendar();
						Date date = cal.getTime();
						SimpleDateFormat dateFormat = new SimpleDateFormat("EEE, dd MMM yyyy HH:mm");
						String time = dateFormat.format(date);
						timeField.setText(time);
						sleep(1000);
					}
				} catch (InterruptedException e) {
					e.printStackTrace();
				}
			}
		};
		clock.start();
	}

	public javax.swing.JTable getIncompleteTaskTable(){
		return incompleteTaskTable;
	}

	public javax.swing.JTable getUpcomingTaskTable(){
		return upcomingTaskTable;
	}

	public javax.swing.JTable getCompletedTaskTable(){
		return completedTaskTable;
	}

	public javax.swing.JTable getAllTaskTable(){
		return allTaskTable;
	}

	public javax.swing.JLabel getStatusField(){
		return statusField;
	}

	public javax.swing.JTabbedPane getTaskTabbedPane(){
		return taskTabbedPane;
	}

	public javax.swing.JTextArea getHelpField(){
		return helpField;
	}

	public javax.swing.JTextField getCommandField(){
		return commandField;
	}


	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        taskTabbedPane = new javax.swing.JTabbedPane();
        incompleteTab = new javax.swing.JPanel();
        incompleteTabScrollPane = new javax.swing.JScrollPane();
        incompleteTaskTable = new javax.swing.JTable();
        upcomingTab = new javax.swing.JPanel();
        upcomingTabScrollPane = new javax.swing.JScrollPane();
        upcomingTaskTable = new javax.swing.JTable();
        completedTab = new javax.swing.JPanel();
        completedTabScrollPane = new javax.swing.JScrollPane();
        completedTaskTable = new javax.swing.JTable();
        allTab = new javax.swing.JPanel();
        allTabScrollPane = new javax.swing.JScrollPane();
        allTaskTable = new javax.swing.JTable();
        helpTab = new javax.swing.JPanel();
        helpTabScrollPane = new javax.swing.JScrollPane();
        helpField = new javax.swing.JTextArea();
        optionTab = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        commandField = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        timeField = new javax.swing.JLabel();
        statusField = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Diamond");
        setBackground(new java.awt.Color(255, 255, 255));
        setFont(new java.awt.Font("DejaVu Serif", 1, 12)); // NOI18N
        setForeground(java.awt.Color.white);
        setIconImages(null);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setRequestFocusEnabled(false);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(""), "Task List", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Comic Sans MS", 1, 12))); // NOI18N
        jPanel4.setRequestFocusEnabled(false);

        taskTabbedPane.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N

        incompleteTabScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        incompleteTabScrollPane.setOpaque(true);

        incompleteTaskTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        incompleteTaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Status", "Title", "Starting Time/Deadline", "Ending Time/ Deadline", "Repeating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        incompleteTaskTable.setToolTipText("");
        incompleteTaskTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        incompleteTaskTable.setColumnSelectionAllowed(true);
        incompleteTaskTable.setFillsViewportHeight(true);
        incompleteTaskTable.setFocusable(false);
        incompleteTaskTable.setGridColor(new java.awt.Color(255, 255, 255));
        incompleteTaskTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        incompleteTabScrollPane.setViewportView(incompleteTaskTable);
        incompleteTaskTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (incompleteTaskTable.getColumnModel().getColumnCount() > 0) {
            incompleteTaskTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            incompleteTaskTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            incompleteTaskTable.getColumnModel().getColumn(2).setPreferredWidth(500);
            incompleteTaskTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            incompleteTaskTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            incompleteTaskTable.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        javax.swing.GroupLayout incompleteTabLayout = new javax.swing.GroupLayout(incompleteTab);
        incompleteTab.setLayout(incompleteTabLayout);
        incompleteTabLayout.setHorizontalGroup(
            incompleteTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(incompleteTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        incompleteTabLayout.setVerticalGroup(
            incompleteTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(incompleteTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        taskTabbedPane.addTab("Incomplete", incompleteTab);

        upcomingTabScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        upcomingTabScrollPane.setOpaque(true);

        upcomingTaskTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        upcomingTaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Status", "Title", "Starting Time/Deadline", "Ending Time/ Deadline", "Repeating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        upcomingTaskTable.setToolTipText("");
        upcomingTaskTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        upcomingTaskTable.setColumnSelectionAllowed(true);
        upcomingTaskTable.setFillsViewportHeight(true);
        upcomingTaskTable.setFocusable(false);
        upcomingTaskTable.setGridColor(new java.awt.Color(255, 255, 255));
        upcomingTaskTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        upcomingTabScrollPane.setViewportView(upcomingTaskTable);
        upcomingTaskTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (upcomingTaskTable.getColumnModel().getColumnCount() > 0) {
            upcomingTaskTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            upcomingTaskTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            upcomingTaskTable.getColumnModel().getColumn(2).setPreferredWidth(500);
            upcomingTaskTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            upcomingTaskTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            upcomingTaskTable.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        javax.swing.GroupLayout upcomingTabLayout = new javax.swing.GroupLayout(upcomingTab);
        upcomingTab.setLayout(upcomingTabLayout);
        upcomingTabLayout.setHorizontalGroup(
            upcomingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(upcomingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(upcomingTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE))
        );
        upcomingTabLayout.setVerticalGroup(
            upcomingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(upcomingTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(upcomingTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        taskTabbedPane.addTab("Upcoming", upcomingTab);

        completedTabScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        completedTabScrollPane.setOpaque(true);

        completedTaskTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        completedTaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Status", "Title", "Starting Time/Deadline", "Ending Time/ Deadline", "Repeating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        completedTaskTable.setToolTipText("");
        completedTaskTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        completedTaskTable.setColumnSelectionAllowed(true);
        completedTaskTable.setFillsViewportHeight(true);
        completedTaskTable.setFocusable(false);
        completedTaskTable.setGridColor(new java.awt.Color(255, 255, 255));
        completedTaskTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        completedTabScrollPane.setViewportView(completedTaskTable);
        completedTaskTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (completedTaskTable.getColumnModel().getColumnCount() > 0) {
            completedTaskTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            completedTaskTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            completedTaskTable.getColumnModel().getColumn(2).setPreferredWidth(500);
            completedTaskTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            completedTaskTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            completedTaskTable.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        javax.swing.GroupLayout completedTabLayout = new javax.swing.GroupLayout(completedTab);
        completedTab.setLayout(completedTabLayout);
        completedTabLayout.setHorizontalGroup(
            completedTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(completedTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(completedTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE))
        );
        completedTabLayout.setVerticalGroup(
            completedTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(completedTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(completedTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        taskTabbedPane.addTab("Completed", completedTab);

        allTabScrollPane.setBackground(new java.awt.Color(255, 255, 255));
        allTabScrollPane.setOpaque(true);

        allTaskTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        allTaskTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "No.", "Status", "Title", "Starting Time/Deadline", "Ending Time/ Deadline", "Repeating"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        allTaskTable.setToolTipText("");
        allTaskTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_LAST_COLUMN);
        allTaskTable.setColumnSelectionAllowed(true);
        allTaskTable.setFillsViewportHeight(true);
        allTaskTable.setFocusable(false);
        allTaskTable.setGridColor(new java.awt.Color(255, 255, 255));
        allTaskTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        allTabScrollPane.setViewportView(allTaskTable);
        allTaskTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        if (allTaskTable.getColumnModel().getColumnCount() > 0) {
            allTaskTable.getColumnModel().getColumn(0).setPreferredWidth(60);
            allTaskTable.getColumnModel().getColumn(1).setPreferredWidth(100);
            allTaskTable.getColumnModel().getColumn(2).setPreferredWidth(500);
            allTaskTable.getColumnModel().getColumn(3).setPreferredWidth(150);
            allTaskTable.getColumnModel().getColumn(4).setPreferredWidth(150);
            allTaskTable.getColumnModel().getColumn(5).setPreferredWidth(150);
        }

        javax.swing.GroupLayout allTabLayout = new javax.swing.GroupLayout(allTab);
        allTab.setLayout(allTabLayout);
        allTabLayout.setHorizontalGroup(
            allTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
            .addGroup(allTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(allTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE))
        );
        allTabLayout.setVerticalGroup(
            allTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
            .addGroup(allTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(allTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE))
        );

        taskTabbedPane.addTab("All tasks", allTab);

        helpField.setColumns(20);
        helpField.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        helpField.setLineWrap(true);
        helpField.setRows(5);
        helpTabScrollPane.setViewportView(helpField);

        javax.swing.GroupLayout helpTabLayout = new javax.swing.GroupLayout(helpTab);
        helpTab.setLayout(helpTabLayout);
        helpTabLayout.setHorizontalGroup(
            helpTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(helpTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 831, Short.MAX_VALUE)
        );
        helpTabLayout.setVerticalGroup(
            helpTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(helpTabScrollPane, javax.swing.GroupLayout.DEFAULT_SIZE, 324, Short.MAX_VALUE)
        );

        taskTabbedPane.addTab("Help", helpTab);

        javax.swing.GroupLayout optionTabLayout = new javax.swing.GroupLayout(optionTab);
        optionTab.setLayout(optionTabLayout);
        optionTabLayout.setHorizontalGroup(
            optionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 831, Short.MAX_VALUE)
        );
        optionTabLayout.setVerticalGroup(
            optionTabLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 324, Short.MAX_VALUE)
        );

        taskTabbedPane.addTab("Option", optionTab);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskTabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 836, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(taskTabbedPane)
        );

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("Please input your command below:");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 791, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE))
        );

        commandField.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        commandField.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(commandField))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(commandField, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setRequestFocusEnabled(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gui/DiamondIcon.png"))); // NOI18N
        jLabel1.setRequestFocusEnabled(false);

        timeField.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        timeField.setName("timeField"); // NOI18N
        timeField.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(62, 62, 62)
                .addComponent(timeField, javax.swing.GroupLayout.PREFERRED_SIZE, 475, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                    .addComponent(timeField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        statusField.setBackground(new java.awt.Color(255, 255, 255));
        statusField.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        statusField.setText("Welcome To Diamond!");
        statusField.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(statusField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(187, 187, 187))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(statusField, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel allTab;
    private javax.swing.JScrollPane allTabScrollPane;
    private javax.swing.JTable allTaskTable;
    private javax.swing.JTextField commandField;
    private javax.swing.JPanel completedTab;
    private javax.swing.JScrollPane completedTabScrollPane;
    private javax.swing.JTable completedTaskTable;
    private javax.swing.JTextArea helpField;
    private javax.swing.JPanel helpTab;
    private javax.swing.JScrollPane helpTabScrollPane;
    private javax.swing.JPanel incompleteTab;
    private javax.swing.JScrollPane incompleteTabScrollPane;
    private javax.swing.JTable incompleteTaskTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel optionTab;
    private javax.swing.JLabel statusField;
    private javax.swing.JTabbedPane taskTabbedPane;
    private javax.swing.JLabel timeField;
    private javax.swing.JPanel upcomingTab;
    private javax.swing.JScrollPane upcomingTabScrollPane;
    private javax.swing.JTable upcomingTaskTable;
    // End of variables declaration//GEN-END:variables
}
